### ISSUE TITLE
Metacritic variable is non-functional

### ISSUE THREAD

**Issue by m1cypher** [CMorooney/obsidian-game-search-plugin#27] opened 2024-06-14 05:27 UTC
please make sure to check [the RAWG API Status page to ensure the API is reportedly functioning](https://status.rawg.io/)

**Describe the bug**
When using the {{metacritic}} variable, it provides "Null" rather than their rating.

**To Reproduce**
1. Add {{metacritic}} to your template
2. Create new note based on template

**Expected behavior**
When using the {{metacritic}} I expected to see the 83 given by [Metacritic review score](https://www.metacritic.com/game/ghost-of-tsushima/) for Ghost of Tsushima in the note I was working on.

**Comment by CMorooney** [comment] 2024-06-14 19:17
hi @m1cypher thanks for opening an issue! At first I was unable to reproduce the problem -- then I saw there were a few different published versions of Ghost of Tsushima that come back from the API

I noticed the Director's cut of the game returned `null` for the metacritic score but the 'vanilla' game returned a score as expected. This seems to be missing data in RAWG's system, as I can see the director's cut [does indeed have a MC rating](https://www.metacritic.com/game/ghost-of-tsushima-directors-cut/)

unfortunately I cannot address the missing data in RAWG's system :( so I will be closing this

<img width="713" alt="Screenshot 2024-06-14 at 3 12 29 PM" src="https://github.com/CMorooney/obsidian-game-search-plugin/assets/1463446/e1a0290a-6bb0-4f6e-a751-2d53d3af5944">
<img width="728" alt="Screenshot 2024-06-14 at 3 12 34 PM" src="https://github.com/CMorooney/obsidian-game-search-plugin/assets/1463446/4cc20e64-9cf5-4348-8390-3a1cb7a626e4">

**Closed by CMorooney** 2024-06-14 19:17 UTC
Labels: bug
